import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Habit } from '../types/habit';
import { UserProfile } from '../types/auth';

export interface ExportData {
  profile?: UserProfile | null;
  habits: Habit[];
  habitMetricsMap?: Record<string, { streakCount: number; longestStreak?: number; totalCompletions?: number }>;
}

/**
 * Exports habit data as a beautifully styled PDF document
 */
export function exportToPDF(data: ExportData): void {
  const { profile, habits, habitMetricsMap = {} } = data;
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const userName = profile?.name || 'HabitFlow User';
  const userEmail = profile?.email || '';
  const exportDate = new Date().toLocaleDateString('en-US', {
    weekday: 'short',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // 1. Header Banner
  doc.setFillColor(0, 99, 152); // #006398 Primary Navy
  doc.rect(0, 0, 210, 32, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('HabitFlow — Habit Progress Report', 14, 18);

  // Subtitle
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('Personal Habit Tracking & Consistency Report', 14, 25);

  // 2. User & Report Metadata Card
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Account Overview', 14, 42);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(70, 70, 70);
  doc.text(`User: ${userName}`, 14, 48);
  if (userEmail) {
    doc.text(`Email: ${userEmail}`, 14, 54);
  }
  doc.text(`Generated: ${exportDate}`, 120, 48);
  doc.text(`Total Habits Tracked: ${habits.length}`, 120, 54);

  // Divider
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.5);
  doc.line(14, 60, 196, 60);

  // 3. Table Rows Construction
  const tableRows = habits.map((habit, index) => {
    const metrics = habitMetricsMap[habit.id] || { streakCount: 0, longestStreak: 0, totalCompletions: 0 };
    const streak = metrics.streakCount ?? 0;
    const category = habit.category || 'General';
    const freq = habit.frequency ? habit.frequency.toUpperCase() : 'DAILY';
    const goal = `${habit.goalCount || 1}x / day`;
    const created = habit.createdAt
      ? new Date(habit.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
      : 'Active';

    return [
      (index + 1).toString(),
      habit.name,
      category,
      freq,
      goal,
      `${streak} days`,
      created,
    ];
  });

  // 4. Render Table with jsPDF AutoTable
  autoTable(doc, {
    startY: 66,
    head: [['#', 'Habit Name', 'Category', 'Frequency', 'Goal', 'Streak', 'Created Date']],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: [0, 99, 152],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 9.5,
      halign: 'left',
    },
    bodyStyles: {
      fontSize: 8.5,
      textColor: [50, 50, 50],
      cellPadding: 3,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 50, fontStyle: 'bold' },
      2: { cellWidth: 35 },
      3: { cellWidth: 25 },
      4: { cellWidth: 20 },
      5: { cellWidth: 24, fontStyle: 'bold', textColor: [180, 83, 9] },
      6: { cellWidth: 32 },
    },
    didDrawPage: (data) => {
      // Footer on every page
      const pageCount = doc.getNumberOfPages();
      doc.setFontSize(8);
      doc.setTextColor(140, 140, 140);
      doc.text(
        'Generated by HabitFlow — Build positive habits with calm momentum',
        14,
        290
      );
      doc.text(
        `Page ${data.pageNumber} of ${pageCount}`,
        196,
        290,
        { align: 'right' }
      );
    },
  });

  // 5. Save & Trigger Download
  const sanitizedName = userName.toLowerCase().replace(/[^a-z0-9]/g, '_');
  const dateStamp = new Date().toISOString().split('T')[0];
  doc.save(`habitflow_report_${sanitizedName}_${dateStamp}.pdf`);
}

/**
 * Exports habit data as an Excel-compatible CSV file with UTF-8 BOM
 */
export function exportToExcel(data: ExportData): void {
  const { profile, habits, habitMetricsMap = {} } = data;
  const userName = profile?.name || 'HabitFlow User';
  const userEmail = profile?.email || '';
  const exportDate = new Date().toISOString();

  // Excel CSV Rows
  const csvLines: string[] = [];

  // Summary Metadata
  csvLines.push(`"HabitFlow Export Report"`);
  csvLines.push(`"User Name","${userName.replace(/"/g, '""')}"`);
  csvLines.push(`"Email","${userEmail.replace(/"/g, '""')}"`);
  csvLines.push(`"Export Timestamp","${exportDate}"`);
  csvLines.push(`"Total Habits Tracked","${habits.length}"`);
  csvLines.push(''); // Empty line divider

  // Column Headers
  csvLines.push(
    [
      '"#"',
      '"Habit Name"',
      '"Category Board"',
      '"Frequency"',
      '"Daily Goal"',
      '"Current Streak (Days)"',
      '"Created Date"',
      '"Status"',
    ].join(',')
  );

  // Table Data Rows
  habits.forEach((h, idx) => {
    const metrics = habitMetricsMap[h.id] || { streakCount: 0 };
    const streak = metrics.streakCount ?? 0;
    const category = h.category || 'General';
    const freq = h.frequency || 'daily';
    const goal = `${h.goalCount || 1} times`;
    const created = h.createdAt
      ? new Date(h.createdAt).toLocaleDateString('en-US')
      : 'N/A';
    const status = h.archived ? 'Archived' : 'Active';

    const row = [
      `"${idx + 1}"`,
      `"${h.name.replace(/"/g, '""')}"`,
      `"${category.replace(/"/g, '""')}"`,
      `"${freq.toUpperCase()}"`,
      `"${goal}"`,
      `"${streak}"`,
      `"${created}"`,
      `"${status}"`,
    ];

    csvLines.push(row.join(','));
  });

  // UTF-8 BOM prefix for Microsoft Excel native UTF-8 recognition
  const csvContent = '\uFEFF' + csvLines.join('\r\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);

  const sanitizedName = userName.toLowerCase().replace(/[^a-z0-9]/g, '_');
  const dateStamp = new Date().toISOString().split('T')[0];

  if (typeof document !== 'undefined') {
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', url);
    downloadAnchor.setAttribute('download', `habitflow_habits_${sanitizedName}_${dateStamp}.csv`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  }
  if (typeof URL !== 'undefined' && URL.revokeObjectURL) {
    URL.revokeObjectURL(url);
  }
}

/**
 * Exports habit data as a standard structured JSON backup
 */
export function exportToJSON(data: ExportData): void {
  const { profile, habits, habitMetricsMap } = data;
  const userName = profile?.name || 'user';
  const exportPayload = {
    app: 'HabitFlow',
    version: '1.0.0',
    exportedAt: new Date().toISOString(),
    user: {
      uid: profile?.uid,
      name: profile?.name,
      email: profile?.email,
      authProvider: profile?.authProvider,
    },
    totalHabits: habits.length,
    habits,
    habitMetrics: habitMetricsMap,
  };

  const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(exportPayload, null, 2));
  const sanitizedName = userName.toLowerCase().replace(/[^a-z0-9]/g, '_');
  const dateStamp = new Date().toISOString().split('T')[0];

  if (typeof document !== 'undefined') {
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `habitflow_backup_${sanitizedName}_${dateStamp}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  }
}
